### ISSUE TITLE
Add instructions for how to install.

### ISSUE THREAD

**Issue by mijoharas** [ddfisher/FreeCAD-CommandPalette#2]
Hi there,

I'm fairly new to freecad, and would appreciate instructions on how to install this macro/plugin. What I can find [in the documentation](https://wiki.freecad.org/Std_AddonMgr) seems concerned with adding plugins from some registry that, unless I'm mistaken, this plugin isn't found in.

I assume that I need to manually clone this repo, and move the files somewhere, but would appreciate confirmation of that fact/instructions on how to install this.

**Comment by ddfisher** [comment]
Yep! You need to copy the [`CommandPalette.FCMacro`](https://github.com/ddfisher/FreeCAD-CommandPalette/blob/main/CommandPalette.FCMacro) file to your [macro directory](https://wiki.freecad.org/How_to_install_macros#Macros_directory).  After doing that, you should be able to add the macro to a toolbar, which will allow you to assign a keyboard shortcut for it.

**Comment by mijoharas** [comment]
Alright, it took me _quite_ a while to get back to my freecad project, but I finally did, and I'd like to thank you for this macro, it seems great!
It'd be awesome if this was directly in the addon manager!

Thanks again.
